baseURL: "https://floriancaumont-cloud.github.io/pm_playbook/"
languageCode: "en-us"
title: "Product Manager Playbook"
theme: "PaperMod"

pagination:
  pagerSize: 20

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  defaultTheme: auto
  ShowReadingTime: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  disableScrollToTop: false
  hideFooter: false
  mainSections: []
menu:
  main:
    - identifier: foundations
      name: Foundations
      url: /01-foundations/
      weight: 1
    - identifier: templates
      name: Templates
      url: /02-templates/
      weight: 2
    - identifier: cases
      name: Case Studies
      url: /03-case-studies/
      weight: 3
    - identifier: frameworks
      name: Frameworks
      url: /04-frameworks/
      weight: 4
    - identifier: resources
      name: Resources
      url: /05-resources/
      weight: 5
    - identifier: tools
      name: Tools
      url: /06-tools/
      weight: 6
